<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\VisionSupport.PlcServer\VisionSupport.PlcServer.csproj" />
    <ProjectReference Include="..\..\src\VisionSupport.MemoryMonitor\VisionSupport.MemoryMonitor.csproj" />
    <ProjectReference Include="..\..\src\VisionSupport.ImageConverter\VisionSupport.ImageConverter.csproj" />
    <ProjectReference Include="..\..\src\VisionSupport.Sam\VisionSupport.Sam.csproj" />
    <ProjectReference Include="..\..\src\VisionSupport.Wireshark\VisionSupport.Wireshark.csproj" />
    <ProjectReference Include="..\..\src\VisionSupport\VisionSupport.csproj" />
  </ItemGroup>

</Project>
